matBaseApp/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace vls.Controllers
{
    [Authorize]
    public class BranchesController : Controller
    {
        // GET: Branches
        public ActionResult Index()
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
    }
}

matBaseApp/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;

namespace vls.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        // GET: Transactions
        public ActionResult Index()
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
    }
}

matBaseApp/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace vls.Controllers
{
    public class SettingsController : Controller
    {
        // GET: Settings
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
    }
}

matBaseApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace vls.Controllers
{
    public class UsersController : Controller
    {
        // GET: VendorNetworks
        [Authorize(Roles = "Administrator,Superman")]
        public ActionResult Index()
        {
            if (User.Identity.GetUserId() == null) return RedirectToAction("Login", "Home");            
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Logout()
        {
            var authenticationManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
            authenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Login", "Home");
        }

        [Authorize]
        public ActionResult ChangePassword()
        {
            if (User.Identity.GetUserId() == null) return RedirectToAction("Login", "Home");            
            return View();
        }
    }
}

matBaseApp/Views/Shared - Copy/_HeaderPage.cshtml
@using Microsoft.AspNet.Identity
@using vls.Classes.Helpers
@using vls.Classes.Repositories
@if (User.Identity.IsAuthenticated)
{
    @Html.AntiForgeryToken()
    var user = new UserRepo().GetUser(User.Identity.GetUserId());
    <div class="ui grid" style="padding: 10px">
        <div class="left floated thirteen wide column">
            <h1 class="ui header">
                <i class="tags icon"></i>
                <div class="content">
                    Instacash
                </div>
            </h1>
        </div>
        <div class="right floated three wide column">
            <h2 class="ui header">
                <div class="ui dropdown item" id="userDropdown">
                    @user.FullName <i class="dropdown icon"></i>
                    <div class="menu">
                        <a class="item" href="@Url.Action("ChangePassword", "Users")">Manage Account</a>
                        <a class="item" href="@Url.Action("Logout","Users" )">Logout</a>
                    </div>
                </div>
            </h2>
        </div>
    </div>@*
    <div class="ui divider"></div>*@
}
else
{
    <div class="ui grid" style="padding: 10px">
        <div class="twelve wide column">
            <h1 class="ui header">
                <i class="tags icon"></i>
                <div class="content">
                    Instacash
                </div>
            </h1>
        </div>
    </div>
    @*<div class="ui divider"></div>*@
}

<script src="~/Content/js/app/user.js"></script>

matBaseApp/Views/Shared - Copy/_HeaderPage2.cshtml
<div class="ui grid" style="padding: 10px">
    <div class="twelve wide column">
        <h2 class="ui header">
            <i class="tags icon"></i>
            <div class="content">
                Instacash
            </div>
        </h2>
    </div>
</div>

<div class="ui divider"></div>

matBaseApp/Views/Shared - Copy/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/css")
    @Scripts.Render("~/js")
    @*<script src="~/Content/js/app.js"></script>*@
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,700,300&subset=latin,vietnamese' rel='stylesheet' type='text/css'>
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="ui inline nag" id="msgPrompt">
        <span class="title">
            <div id="msgPromptText"></div>
        </span>
        <i class="close icon"></i>
    </div>
    @using Microsoft.AspNet.Identity
    @using vls.Classes.Helpers
    @if (User.Identity.IsAuthenticated)
    {
        @Html.AntiForgeryToken()
        <div class="ui grid" style="height: 100%">
            @Html.Partial("_Menu")
            <div class="row" style="height: 100%">
                @*<div class="two wide column" style="margin-top: -15px; height: 100%;" id="mainSidebar">
                @Html.Partial("_NavigationPage")
            </div>*@
                <div class="sixteen wide column" style="padding-left: 20px; padding-right: 10px">
                    @*@Html.Partial("_HeaderPage")*@
                    @*@Html.Partial("_Menu")*@
                    @RenderBody()
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="ui grid">
            <div class="row">
                <div class="sixteen wide column">
                    @Html.Partial("_HeaderPage2")
                    @RenderBody()
                </div>
            </div>
        </div>
    }
</body>
</html>

matBaseApp/Views/Shared - Copy/_Menu.cshtml
@using Microsoft.AspNet.Identity
@using vls.Classes.Helpers
@using vls.Classes.Repositories
@if (User.Identity.IsAuthenticated)
{
    @Html.AntiForgeryToken()
    var user = new UserRepo().GetUser(User.Identity.GetUserId());

    <div class="ui inverted large menu" id="MainMenu" >
        <a class="item" href="@Url.Action("Index", "Home")">
            <img class="circular ui image" src="/Content/images/logo.jpg" alt="logo" style="width: 40px; height: 40px;">
        </a>
        <a class="item" href="@Url.Action("Index", "Home")">
            <i class="icon dashboard" title="Dashboard"></i>
            Dashboard
        </a>
        @if (User.IsInRole("Agent"))
        {
            <a class="item" href="@Url.Action("Send", "Home")">
                <i class="icon mail" title="Send Money"></i>
                Send Money
            </a>
        }
        @if (User.IsInRole("Agent"))
        {
            <a class="item" href="@Url.Action("Recieve", "Home")">
                <i class="icon book" title="Pay Money"></i>
                Pay Money
            </a>
        }
        @if (User.IsInRole("Agent"))
        {
            <a class="item" href="@Url.Action("Cancel", "Home")">
                <i class="icon remove circle" title="Cancel Transfer"></i>
                Cancel Transfer
            </a>
        }
        @if (User.IsInRole("Administrator"))
        {
            <a class="item" href="@Url.Action("Reverse", "Home")">
                <i class="icon recycle" title="Reverse Transaction"></i>
                Reverse Transaction
            </a>
        }
        @if (User.IsInRole("Administrator"))
        {
            <a class="item" href="@Url.Action("Index", "Branches")">
                <i class="icon building" title="Branches"></i>
                Branches
            </a>
        }
        @if (User.IsInRole("Administrator") || User.IsInRole("Audit"))
        {
            <a class="item" href="@Url.Action("Index", "Reports")">
                <i class="icon ticket" title="Reports"></i>
                Reports
            </a>
        }
        
        @if (User.IsInRole("Administrator"))
        {
            <a class="item" href="@Url.Action("Index", "Users")" title="Users">
                <i class="icon users" title="Users"></i>
                Users
            </a>
        }

        @if (User.IsInRole("Administrator"))
        {
            <a class="item" href="@Url.Action("Index", "Settings")" title="Settings">
                <i class="icon settings"></i>
                Settings
            </a>
        }
        <div class="right menu">
            <div class="ui dropdown item" id="userDropdown">
                @user.FullName <i class="dropdown icon"></i>
                <div class="menu">
                    <a class="item" href="@Url.Action("ChangePassword", "Users")" title="Manage Profile">
                        <i class="icon write square"></i>
                        Change Password
                    </a>
                    <a class="item" href="@Url.Action("Logout", "Users")" title="Logout">
                        <i class="icon sign out"></i>
                        Logout
                    </a>
                </div>
            </div>
        </div>

    </div>
    <div class="ui inverted large menu" id="ResponsiveMenu" >
        <a class="item" href="@Url.Action("Index", "Home")">
            InstaCash
        </a>
        <div class="ui dropdown item" id="menuDropdown">
            <i class="icon list layout" title="Menu"></i>
            Menu <i class="dropdown icon"></i>
            <div class="menu">
                <a class="item" href="@Url.Action("Index", "Home")">
                    <i class="icon dashboard" title="Dashboard"></i>
                    Dashboard
                </a>
                @if (User.IsInRole("Agent"))
                {
                    <a class="item" href="@Url.Action("Send", "Home")">
                        <i class="icon mail" title="Send Money"></i>
                        Send Money
                    </a>
                }
                @if (User.IsInRole("Agent"))
                {
                    <a class="item" href="@Url.Action("Recieve", "Home")">
                        <i class="icon book" title="Pay Money"></i>
                        Pay Money
                    </a>
                }
                @if (User.IsInRole("Agent"))
                {
                    <a class="item" href="@Url.Action("Cancel", "Home")">
                        <i class="icon remove circle" title="Cancel Transfer"></i>
                        Cancel Transfer
                    </a>
                }
                @if (User.IsInRole("Administrator"))
                {
                    <a class="item" href="@Url.Action("Reverse", "Home")">
                        <i class="icon recycle" title="Reverse Transaction"></i>
                        Reverse Transaction
                    </a>
                }
                @if (User.IsInRole("Administrator"))
                {
                    <a class="item" href="@Url.Action("Index", "Branches")">
                        <i class="icon building" title="Branches"></i>
                        Branches
                    </a>
                }
                @if (User.IsInRole("Administrator") || User.IsInRole("Audit"))
                {
                    <a class="item" href="@Url.Action("Index", "Reports")">
                        <i class="icon ticket" title="Reports"></i>
                        Reports
                    </a>
                }
                @if (User.IsInRole("Administrator"))
                {
                    <a class="item" href="@Url.Action("Index", "Users")" title="Users">
                        <i class="icon users" title="Users"></i>
                        Users
                    </a>
                }

                @if (User.IsInRole("Administrator"))
                {
                    <a class="item" href="@Url.Action("Index", "Settings")" title="Settings">
                        <i class="icon settings"></i>
                        Settings
                    </a>
                }
                <div class="ui dropdown item" id="userDropdown">
                    @user.FullName <i class="dropdown icon"></i>
                    <div class="menu">
                        <a class="item" href="@Url.Action("ChangePassword", "Users")" title="Manage Profile">
                            <i class="icon write square"></i>
                            Change Password
                        </a>
                        <a class="item" href="@Url.Action("Logout", "Users")" title="Logout">
                            <i class="icon sign out"></i>
                            Logout
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ui divider"></div>

}
<script src="~/Content/js/app/menu.js"></script>

matBaseApp/Views/Shared - Copy/_NavigationPage.cshtml
@if (User.Identity.IsAuthenticated)
{
    @Html.AntiForgeryToken()
    <div id="mainSidebarContent" class="ui left vertical inverted labeled icon menu" style="height: 100%;  margin-bottom: -40px;">
        <a class="item" href="@Url.Action("Index","Home" )">
            <img class="circular ui image" src="/Content/images/logo.jpg" alt="logo" style="width: 92px; height: 92px;">
        </a>
        <a class="item" href="@Url.Action("Index","Home" )">
            <i class="icon dashboard"></i>
            Dashboard
        </a>
        @if (User.IsInRole("Administrator") || User.IsInRole("Agent"))
        {
            <a class="item" href="@Url.Action("Send","Home" )">
                <i class="icon mail"></i>
                Send Money
            </a>
        }
        @if (User.IsInRole("Administrator") || User.IsInRole("Agent"))
        {
            <a class="item" href="@Url.Action("Recieve","Home" )">
                <i class="icon book"></i>
                Pay Money
            </a>
        }
        @if (User.IsInRole("Administrator") || User.IsInRole("Agent"))
        {
            <a class="item" href="@Url.Action("Cancel","Home" )">
                <i class="icon sign out"></i>
                Cancel Transfer
            </a>
        }
        @if (User.IsInRole("Administrator"))
        {
            <a class="item" href="@Url.Action("Reverse","Home" )">
                <i class="icon recycle"></i>
                Reverse Transaction
            </a>
        }
        @if (User.IsInRole("Administrator"))
        {
            <a class="item" href="@Url.Action("Index","Branches" )">
                <i class="icon building"></i>
                Branches
            </a>
        }
        <a class="item" href="@Url.Action("Index","Reports" )">
            <i class="icon ticket"></i>
            Reports
        </a>
        @if (User.IsInRole("Administrator"))
        {
            <a class="item" href="@Url.Action("Index","Users" )">
                <i class="icon users"></i>
                Users
            </a>
        }

        @if (User.IsInRole("Administrator"))
        {
            <a class="item" href="@Url.Action("Index","Settings" )">
                <i class="icon settings"></i>
                Settings
            </a>
        }

    </div>
}